### ISSUE TITLE
plugin: integration: gracefully handle API calls that require authentication

### ISSUE THREAD

**Issue by lekkas** [resin-io-modules/scrutinizer#8]
If no `GITHUB_TOKEN` is passed the `integration` plugin will throw an exception e.g.

```
Unhandled rejection {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/branches/#get-required-status-checks-of-protected-branch"}
```

I *think* this (i.e. unauthenticated request) should be handled internally by the plugin, one way would be to default to an empty plugin list and maybe print an info message that a token is required.

**Comment by jviotti** [comment]
Even better, we can add proper error handling for these cases on the GitHubBackend class.
